- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install Ansible
      apt:
        name:
          - htop
          - mc
          - tmux
          - ncdu
          - zsh
          - vim-nox
          - curl
          - git
          - ncdu
          - neofetch
          - nnn
          - npm
