- name: install packages on all hosts
  hosts: "*"
  tasks:
    - name: Install Packages
      apt:
        name:
          - zsh
          - tmux
          - vim-nox
          - curl
          - git
          - ncdu
          - htop
          - neofetch
          - nnn
          - npm
        state: present
        update_cache: true
      become: true

    # - name: Install BTop
    #   community.general.snap:
    #     name:
    #       - btop

